### PR TITLE
Scala Labs: 0, 1, 2, 4

### PR DESCRIPTION
**Pull request by noikaslev**
I modified the prop-prices.csv file. I added seconds in the date field

### CODE REVIEW

**Comment by goldshtn** [comment]
Thanks! Not sure why you had to modify the CSV file. I would much rather to leave the original dataset intact. If any preprocessing is necessary it needs to be done on the Scala side. Can you make that work?

**Comment by noikaslev** [comment]
I refactored the Lab4. Changed the date field to string type and using substring function to get year/month.

**Comment by goldshtn** [comment]
Did you push your changes back to this branch? I still see the .csv file as being modified as part of this PR.

**Comment by noikaslev** [comment]
Not yet, I want to add Lab5 (Twitter)

**Comment by goldshtn** [comment]
@noikaslev If you delete the .csv file from your local repo and push it to the fork, you'll be able to sync this PR and get the delete commit here. But even better would be to rebase on your side so that the .csv file doesn't even enter history. Let me (or @eyalbenivri) know over email if you need help with this.

**Comment by goldshtn** [comment]
Lev, I don't really want one huge PR that has all the labs in it. Please update what the status is on the different labs and the comments that were raised on this PR earlier. If all the labs are ok, I would really like to merge the ones you have ready and then do smaller PRs going forward. @noikaslev

**Comment by noikaslev** [comment]
I updated what we discussed on the first PR, and added Lab 3

**Comment by goldshtn** [comment]
@noikaslev: I am merging this, thanks. For the next labs, please open a separate PR for each lab. Also, when you're done, please review the labs you already ported for grammar and punctuation -- there are some typos and incomplete sentences. Thanks!

**Pull request merged**
